# NumPy

In [3]:
import numpy as np

## Array

Vector : 3i + 2j + 3k --> 1D

Matrix :  --> 2D

         [1 0 1 
          1 1 1
          0 0 1]

In [4]:
a = np.array([3,2,3])

In [5]:
print(a)

[3 2 3]


In [6]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(0,1,0.02)

array([0.  , 0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 ,
       0.22, 0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 , 0.42,
       0.44, 0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 , 0.62, 0.64,
       0.66, 0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 , 0.82, 0.84, 0.86,
       0.88, 0.9 , 0.92, 0.94, 0.96, 0.98])

In [10]:
a

array([3, 2, 3])

In [17]:
mylist = [1,2,3,4,5,6]
mylist.append([2,3])
mylist[-1]

[2, 3]

In [13]:
np.append(a, [2,3])

array([3, 2, 3, 2, 3])

In [18]:
np.delete(a, 2)

array([3, 2])

In [19]:
arr = np.array([10,4,3,19,2,1,6,18])

In [20]:
arr

array([10,  4,  3, 19,  2,  1,  6, 18])

In [22]:
np.sort(arr)

array([ 1,  2,  3,  4,  6, 10, 18, 19])

## Shape and size

In [28]:
arr2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
    
])

In [29]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
arr2.shape

(3, 4)

In [34]:
arr2.ndim

2

## Resahping

In [35]:
print(arr)
print(arr.shape)

[10  4  3 19  2  1  6 18]
(8,)


In [38]:
arr_reshape = arr.reshape(4,2)

In [39]:
arr_reshape.ndim

2

In [40]:
arr.reshape(2,2,2)

array([[[10,  4],
        [ 3, 19]],

       [[ 2,  1],
        [ 6, 18]]])

In [42]:
arr[np.newaxis].shape

(1, 8)

In [43]:
arr.reshape(8,1)

array([[10],
       [ 4],
       [ 3],
       [19],
       [ 2],
       [ 1],
       [ 6],
       [18]])

In [44]:
arr[: , np.newaxis].shape

(8, 1)

In [48]:
np.expand_dims(arr,axis=1)

array([[10],
       [ 4],
       [ 3],
       [19],
       [ 2],
       [ 1],
       [ 6],
       [18]])

## Indexing dan Slicing

In [49]:
mylist = [1,2,3,4,5,6,7,8]

In [50]:
mylist[1:4]

[2, 3, 4]

In [51]:
mylist[-1]

8

In [52]:
data = np.array([1,2,3,4,5,6,7,8])

In [53]:
data[0]

1

In [54]:
data[-2:]

array([7, 8])

In [56]:
data[data >= 4]

array([4, 5, 6, 7, 8])

In [57]:
data[data%2 == 0]

array([2, 4, 6, 8])

In [59]:
data[(data > 3) & (data%2==0)]

array([4, 6, 8])

In [60]:
arr

array([10,  4,  3, 19,  2,  1,  6, 18])

In [61]:
arr1 = arr[0:4]
arr2 = arr[4:]

In [62]:
arr1

array([10,  4,  3, 19])

In [63]:
arr2

array([ 2,  1,  6, 18])

In [64]:
np.vstack((arr1,arr2))

array([[10,  4,  3, 19],
       [ 2,  1,  6, 18]])

In [66]:
a1 = np.array([
    [1,1],
    [2,2]
])

a2 = np.array([
    [3,3],
    [4,4]
])

In [67]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [69]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [74]:
arrsplit = np.array([
    [1,2,3,4,5,6,7,8,9,10,11,12],
    [13,14,15,16,17,18,19,20,21,22,23,24]
])

In [75]:
np.hsplit(arrsplit, 4)

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

## Copy Array

In [76]:
arr

array([10,  4,  3, 19,  2,  1,  6, 18])

In [77]:
arr2 = arr.copy()

In [79]:
arr2 * 2

array([20,  8,  6, 38,  4,  2, 12, 36])

## Basic Operation

In [80]:
v1 = np.array([2,3,5])
v2 = np.array([1,2,2])

In [81]:
v1 + v2

array([3, 5, 7])

In [83]:
v2 -  v1

array([-1, -1, -3])

In [84]:
v1 * v2

array([ 2,  6, 10])

In [85]:
v1/v2

array([2. , 1.5, 2.5])

In [86]:
data.sum()

36

In [91]:
a1.sum(axis=0)

array([3, 3])

In [93]:
v1

array([2, 3, 5])

In [94]:
v1 * .5

array([1. , 1.5, 2.5])

In [97]:
M = np.arange(0,16).reshape(4,4)

In [100]:
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [98]:
M.sum(axis=0)

array([24, 28, 32, 36])

In [99]:
M.max()

15

In [102]:
M.min(axis=0)

array([0, 1, 2, 3])

In [103]:
M.min()

0

In [105]:
M.std(axis=1)

array([1.11803399, 1.11803399, 1.11803399, 1.11803399])

In [106]:
M.mean(axis=1)

array([ 1.5,  5.5,  9.5, 13.5])

## Matrix

In [110]:
#np.ones((3,3))
#np.zeros((3,3))
np.random.random((3,3))

array([[0.93098837, 0.36430189, 0.31210769],
       [0.9033458 , 0.39868644, 0.81197498],
       [0.52418592, 0.4076722 , 0.44074225]])

In [111]:
mat = np.array([

    [1,2],
    [3,4]
])

In [112]:
ones = np.ones((2,2))

In [113]:
mat + ones

array([[2., 3.],
       [4., 5.]])

In [114]:
mat + 5

array([[6, 7],
       [8, 9]])

In [116]:
mat * mat

array([[ 1,  4],
       [ 9, 16]])

In [118]:
np.matmul(mat,mat)

array([[ 7, 10],
       [15, 22]])

In [120]:
M = np.random.random((5,5))

In [121]:
M

array([[0.56311656, 0.05266167, 0.9534692 , 0.93839904, 0.74567514],
       [0.80419273, 0.80734187, 0.20785039, 0.66255989, 0.06736999],
       [0.15430785, 0.16236133, 0.84558909, 0.76873376, 0.87686987],
       [0.54832087, 0.61974985, 0.51682402, 0.86890693, 0.15239819],
       [0.54712092, 0.01894846, 0.3294271 , 0.51223798, 0.7149831 ]])

In [122]:
M[1,1]

0.8073418711515854

In [123]:
M[2, 1:4]

array([0.16236133, 0.84558909, 0.76873376])

In [124]:
M.max(axis=0)

array([0.80419273, 0.80734187, 0.9534692 , 0.93839904, 0.87686987])

In [147]:
M

array([[0.56311656, 0.05266167, 0.9534692 , 0.93839904, 0.74567514],
       [0.80419273, 0.80734187, 0.20785039, 0.66255989, 0.06736999],
       [0.15430785, 0.16236133, 0.84558909, 0.76873376, 0.87686987],
       [0.54832087, 0.61974985, 0.51682402, 0.86890693, 0.15239819],
       [0.54712092, 0.01894846, 0.3294271 , 0.51223798, 0.7149831 ]])

## Inverse

In [152]:
np.dot(mat,np.linalg.inv(mat))

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

Solve 
x + 2y = 1
3x + 5y = 1

[1 2] [1]
[3 5] [2]

In [155]:
mat_per = np.array([
    [1,2],
    [3,4]
])

mat_has = np.array([1,2])
np.linalg.solve(mat_per, mat_has)

array([0. , 0.5])

## Transpose

In [131]:
Mat = np.array([
    [1,2],
    [3,4],
    [5,6]
])

In [132]:
Mat.T.shape

(2, 3)

In [133]:
mat_transposed = Mat.T

In [134]:
mat_transposed.reshape(6,1)

array([[1],
       [3],
       [5],
       [2],
       [4],
       [6]])

In [138]:
one_3d = np.ones((3,3,3))

In [141]:
one_3d = np.random.random((3,3,3))

In [142]:
one_3d.mean()

0.4085195288477089

In [143]:
one_3d.shape

(3, 3, 3)

In [145]:
one_3d.reshape((27,))

array([0.23000894, 0.781687  , 0.88693977, 0.86523073, 0.42814015,
       0.07147058, 0.07949134, 0.46792467, 0.82901543, 0.7670163 ,
       0.73140988, 0.09754826, 0.33193916, 0.6151025 , 0.96679623,
       0.00924744, 0.22060753, 0.04719534, 0.12835476, 0.8201285 ,
       0.07768137, 0.20842037, 0.3925448 , 0.01469419, 0.50143668,
       0.00753529, 0.45246008])

In [146]:
one_3d.flatten()

array([0.23000894, 0.781687  , 0.88693977, 0.86523073, 0.42814015,
       0.07147058, 0.07949134, 0.46792467, 0.82901543, 0.7670163 ,
       0.73140988, 0.09754826, 0.33193916, 0.6151025 , 0.96679623,
       0.00924744, 0.22060753, 0.04719534, 0.12835476, 0.8201285 ,
       0.07768137, 0.20842037, 0.3925448 , 0.01469419, 0.50143668,
       0.00753529, 0.45246008])

In [156]:
data_aktual = np.random.random(100)

In [157]:
data_prediksi = np.random.random(100)

In [162]:
(1/len(data_aktual)) * np.sum(np.square(data_aktual - data_prediksi))

0.16773396744906074